{
  "openapi": "3.1.0",
  "info": {
    "title": "Todolist RESTful API",
    "version": "1.0.0",
    "description": "A simple RESTful API for managing a to-do list.",
    "termsOfService": "https://example.com/terms",
    "contact": {
      "name": "Gendhi Ramona",
      "url": "https://gendhiramona.site",
      "email": "gendhiramona@gmail.com"
    },
    "license": {
      "name": "APACHE 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": [
    {
      "description": "Todolist RESTful API Server",
      "url": "https://{environment}.gendhiramona.site/api/v1/",
      "variables": {
        "environment": {
          "default": "dev",
          "descriptions": "The environment to use for the API.",
          "enum": [
            "dev",
            "prod"
          ]
        }
      }
    }
  ],
  "externalDocs": {
    "description": "Github Repository",
    "url": "https://github.com/xdranel/todolist-api"
  },
  "paths": {
    "/todolist": {
      "get": {
        "security": [
          {
            "todolist_auth": []
          }
        ],
        "tags": [
          "Todolist"
        ],
        "summary": "Get all todolist",
        "description": "Get all active todolist by default",
        "parameters": [
          {
            "name": "include_completed",
            "in": "query",
            "required": false,
            "description": "Include completed todolist in result",
            "schema": {
              "type": "boolean",
              "nullable": true,
              "default": false
            }
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "description": "Filter todolist by name",
            "schema": {
              "type": "string",
              "nullable": true,
              "minLength": 1,
              "maxLength": 255
            },
            "examples": {
              "java": {
                "description": "Example name Java",
                "value": "Java"
              },
              "php": {
                "description": "Example name PHP",
                "value": "PHP"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success get all todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ArrayTodolist"
                },
                "examples": {
                  "success": {
                    "description": "Example success get all todolist",
                    "value": [
                      {
                        "id": "1",
                        "name": "Java",
                        "priority": 1,
                        "tags": [
                          "java",
                          "spring"
                        ]
                      },
                      {
                        "id": "2",
                        "name": "PHP",
                        "priority": 2,
                        "tags": [
                          "php",
                          "laravel"
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "todolist_auth": []
          }
        ],
        "tags": [
          "Todolist"
        ],
        "summary": "Create a new todolist",
        "description": "Create a new todolist to database",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrUpdateTodolist"
              },
              "examples": {
                "java": {
                  "description": "Example create todolist Java",
                  "value": {
                    "name": "Java",
                    "tags": [
                      "java",
                      "spring"
                    ],
                    "priority": 1
                  }
                },
                "php": {
                  "description": "Example create todolist PHP",
                  "value": {
                    "name": "PHP",
                    "tags": [
                      "php",
                      "laravel"
                    ],
                    "priority": 2
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success create todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todolist"
                },
                "examples": {
                  "java": {
                    "description": "Example success create todolist Java",
                    "value": {
                      "id": "1",
                      "name": "Java",
                      "priority": 1,
                      "tags": [
                        "java",
                        "spring"
                      ]
                    }
                  },
                  "php": {
                    "description": "Example success create todolist PHP",
                    "value": {
                      "id": "2",
                      "name": "PHP",
                      "priority": 2,
                      "tags": [
                        "php",
                        "laravel"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/todolist/{todolistId}": {
      "put": {
        "security": [
          {
            "todolist_auth": []
          }
        ],
        "tags": [
          "Todolist"
        ],
        "summary": "Update existing todolist",
        "description": "Update existing todolist in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/todolistId"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrUpdateTodolist"
              },
              "examples": {
                "java": {
                  "description": "Example create todolist Java",
                  "value": {
                    "name": "Java",
                    "tags": [
                      "java",
                      "spring"
                    ],
                    "priority": 1
                  }
                },
                "php": {
                  "description": "Example create todolist PHP",
                  "value": {
                    "name": "PHP",
                    "tags": [
                      "php",
                      "laravel"
                    ],
                    "priority": 2
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success update todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todolist"
                },
                "examples": {
                  "java": {
                    "description": "Example success update todolist Java",
                    "value": {
                      "id": "1",
                      "name": "Java",
                      "priority": 1,
                      "tags": [
                        "java",
                        "spring"
                      ]
                    }
                  },
                  "php": {
                    "description": "Example success update todolist PHP",
                    "value": {
                      "id": "2",
                      "name": "PHP",
                      "priority": 2,
                      "tags": [
                        "php",
                        "laravel"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "todolist_auth": []
          }
        ],
        "tags": [
          "Todolist"
        ],
        "summary": "Delete existing todolist",
        "description": "Delete existing todolist in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/todolistId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success delete todolist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Example success delete todolist",
                    "value": {
                      "success": true
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Failed delete todolist, not found todolist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "failed": {
                    "description": "Failed delete todolist, not found todolist",
                    "value": {
                      "success": false
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "todolist_auth": {
        "description": "Authentication for Todolist RESTful API",
        "type": "apiKey",
        "in": "header",
        "name": "X-API-KEY"
      }
    },
    "parameters": {
      "todolistId": {
        "name": "todolistId",
        "in": "path",
        "required": true,
        "description": "The id of the todolist to update",
        "schema": {
          "type": "string",
          "minLength": 1
        },
        "examples": {
          "java": {
            "description": "Sample todolist id for Java",
            "value": "1"
          },
          "php": {
            "description": "Sample todolist id for PHP",
            "value": "2"
          }
        }
      }
    },
    "schemas": {
      "Todolist": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "priority": {
            "type": "number",
            "format": "int32"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "CreateOrUpdateTodolist": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "required": true
          },
          "priority": {
            "type": "number",
            "format": "int32",
            "required": true,
            "default": 1
          },
          "tags": {
            "type": "array",
            "required": false,
            "items": {
              "type": "string"
            }
          }
        }
      },
      "ArrayTodolist": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Todolist"
        }
      }
    }
  }
}

